# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
old_fashioned = Category.create!(name: "Old-Fashioned")
filled = Category.create!(name: "Filled")
seasonal = Category.create!(name: "Seasonal")

dunkin = Shop.create!(name: "Dunkin' Donuts", address: "56 Westview Lane", city: "Pittsburgh", state: "PA", url: "www.google.com", phone: "123-456-7890", photo_url: "https://c1.staticflickr.com/5/4043/4431290508_b920a793f5_z.jpg?zz=1" )
boston_cream_dd = Donut.create!(name: "Boston Cream Donut", category: filled, shop: dunkin)
honey_maple_dd = Donut.create!(name: "Honey Maple Donut", category: old_fashioned, shop: dunkin)
syrup_glaze_dd = Donut.create!(name: "Syrup Glaze Donut", category: old_fashioned, shop: dunkin)
chocolate_glaze_dd = Donut.create!(name: "Chocolate Glaze Donut", category: old_fashioned, shop: dunkin)
french_crueller_dd = Donut.create!(name: "French Crueller", category: seasonal, shop: dunkin)

honeydew = Shop.create!(name: "Honeydew Donuts", address: "1600 Pennsylvia Ave NW", city: "Washington, DC", state: "DC", url:"www.honeydewrules.org", phone:"111-111-1112", photo_url: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Honey_Dew_Donuts.jpg")
jelly_hd = Donut.create!(name: "Jelly Donut", category: filled, shop: honeydew)

union_square = Shop.create!(name: "Union Square Donuts", address: "55 Bow Street", city: "Somerville", state: "MA", url:"www.donutsarecool.web", phone:"222-222-2222", photo_url: "https://pbs.twimg.com/profile_images/943886158026612738/Bp7wYYav_400x400.jpg")
sugar_raised_us = Donut.create!(name: "Sugar-Raised Donut", category: old_fashioned, shop: union_square)
maple_bacon_us = Donut.create!(name: "Maple Bacon Donut", category: old_fashioned, shop: union_square)
vietnamese_us = Donut.create!(name: "Vietnamese Donut", category: old_fashioned, shop: union_square)
vanilla_bean_us = Donut.create!(name: "Vanilla Bean Donut", category: old_fashioned, shop: union_square)
honey_glazed_us = Donut.create!(name: "Honey Glaze Donut", category: old_fashioned, shop: union_square)
cinnamon_sugar_us = Donut.create!(name: "Cinnamon Sugar Donut", category: old_fashioned, shop: union_square)
pumpkin_spice_us = Donut.create!(name: "Pumpkin Spice Donut", category: seasonal, shop: union_square)
apple_cide_cake_us = Donut.create!(name: "Apple Cider Cake Donut", category: seasonal, shop: union_square)
butternut_us = Donut.create!(name: "Butternut Donut", category: old_fashioned, shop: union_square)
boston_cream_us = Donut.create!(name: "Boston Cream Pie Donut", category: filled, shop: union_square)
coconut_glaze_us = Donut.create!(name: "Coconut Glazed Donut", category: old_fashioned, shop: union_square)

kanes = Shop.create!(name: "Kane's Donuts", address: "90 Oliver St", city: "Boston", state: "MA", url:"www.kanesdonunts.com", phone:"857-317-2654", photo_url: "https://cdn.vox-cdn.com/thumbor/7bCGPy0vsr_pqQR71x3UEoQAikc=/0x0:600x424/1200x800/filters:focal(255x64:351x160)/cdn.vox-cdn.com/uploads/chorus_image/image/52193935/Kane_s.0.0.jpeg")
honey_dip_kanes = Donut.create!(name: "Honey Dip Donut", category: old_fashioned, shop: kanes)
boston_cream_kanes = Donut.create!(name: "Boston Cream Donut", category: filled, shop: kanes)
chocolate_honey_dip_kanes = Donut.create!(name: "Chocolate Honey Dip Donut", category: old_fashioned, shop: kanes)
butter_crunch_kanes = Donut.create!(name: "Butter Crunch Donut", category: old_fashioned, shop: kanes)
creme_brulee_kanes = Donut.create!(name: "Creme Brulee Donut", category: old_fashioned, shop: kanes)
raspberry_jelly_kanes = Donut.create!(name: "Raspberry Jelly Donut", category: filled, shop: kanes)
maine_blueberry_kanes = Donut.create!(name: "Maine Blueberry Donut", category: old_fashioned, shop: kanes)
almond_joy_kanes = Donut.create!(name: "Almond Joy Donut", category: seasonal, shop: kanes)
dark_cloud_kanes = Donut.create!(name: "Dark Cloud Donut", category: seasonal, shop: kanes)
blueberry_crumble_kanes = Donut.create!(name: "Blueberry Crumble Donut", category: seasonal, shop: kanes)
ginger_beer_kanes = Donut.create!(name: "Ginger Beer Donut", category: seasonal, shop: kanes)
pistachio_kanes = Donut.create!(name: "Pistachio Donut", category: seasonal, shop: kanes)

black_bird = Shop.create!(name: "Black Bird Doughnuts", address: "492 Tremont St", city: "Boston", state: "MA", url:"blackbirddoughnuts.com", phone:"617-482-9000", photo_url: "https://cdn10.bostonmagazine.com/wp-content/uploads/sites/2/2017/01/Blackbird-Doughnuts-Boston-cream.jpg")
vanilla_glazed_bb = Donut.create!(name: "Vanilla Glazed Donut", category: old_fashioned, shop: black_bird)
salted_toffee_bb = Donut.create!(name: "Salted Toffee Donut", category: old_fashioned, shop: black_bird)
boston_cream_bb = Donut.create!(name: "Boston Cream Bismarck Donut", category: filled, shop: black_bird)
everything_bagel_bb = Donut.create!(name: "Everything Bagel Donut", category: filled, shop: black_bird)
pumpkin_cheesecake_bb = Donut.create!(name: "Pumpkin Cheesecake Donut", category: seasonal, shop: black_bird)
apple_cider_bb = Donut.create!(name: "Apple Cider Donut", category: seasonal, shop: black_bird)

roche_bros = Shop.create!(name: "Roche Bros.", address: "8 Summer Street", city: "Boston", state: "MA", url:"www.rochebros.com", phone:"617-867-5309", photo_url: "https://upload.wikimedia.org/wikipedia/commons/9/93/Roche_Bros%2C_West_Roxbury_MA.jpg")
pumpkin_rb = Donut.create!(name: "Pumpkin Donut", category: old_fashioned, shop: roche_bros)

boston_common_coffee = Shop.create!(name: "Boston Common Coffee Co.", address: "10 High Street", city: "Boston", state: "MA", url:"www.bostoncommoncoffee.com", phone:"617-695-9700", photo_url: "https://dakiniland.files.wordpress.com/2014/10/boston-common-coffee-company.jpg")
bavarian_cream_bc = Donut.create!(name: "Bavarian Cream Donut", category: seasonal, shop: boston_common_coffee)
chocolate_cake_bc = Donut.create!(name: "Chocolate Cake Donut", category: seasonal, shop: boston_common_coffee)
apple_crumble_bc = Donut.create!(name: "Apple Crumble Donut", category: seasonal, shop: boston_common_coffee)

randalls_farm = Shop.create!(name: "Randall's Farm & Greenhouse", address: "631 Center Street", city: "Ludlow", state: "MA", url:"randallsfarm.net", phone:"413-589-7071", photo_url: "https://explorewesternmass.com/wp-content/uploads/2018/02/randalls-farm.jpg")
cider_donut_rf = Donut.create!(name: "Cider Donut", category: seasonal, shop: randalls_farm)


review1 = Review.create!(rating: 4, body: "this is the best donut i have ever tasted in my 7 years on this earth", price_range: "1", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glazed-Donut.jpg/1200px-Glazed-Donut.jpg", donut: sugar_raised_us, shop: union_square )
review2 = Review.create!(rating: 2, body: "this is a very mediocre and not exciting donut", price_range: "2", photo_url: "https://www.theflavorbender.com/wp-content/uploads/2014/09/Simpsons-Doughnuts-4238-Copy-1.jpg", donut: jelly_hd, shop: honeydew)

fav_donuts_1 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/5k9y1ifcahjbpu6/IMG_0066.JPG?raw=1")
fav_donuts_2 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/r4zcj1cp623wtbx/IMG_0067.JPG?raw=1")
fav_donuts_3 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/o7cgf3yx21y20b1/IMG_0068.JPG?raw=1")
fav_donuts_4 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/b6m0sy2q738ocib/IMG_0069.JPG?raw=1")
fav_donuts_5 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/c00qcrwvsl636lj/IMG_0070.JPG?raw=1")
fav_donuts_6 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/74mbwn4izutqm4g/IMG_0071.JPG?raw=1")
fav_donuts_7 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/zeclsj3b8z6hrza/IMG_0072.JPG?raw=1")
fav_donuts_8 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/2ktae55uggdh3pk/IMG_0073.JPG?raw=1")
fav_donuts_9 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/b7zkjo4b9trej0e/IMG_0074.JPG?raw=1")
fav_donuts_10 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/29nam2m03mwg8o0/IMG_0075.JPG?raw=1")
fav_donuts_11 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/424wkjxe92ghyen/IMG_0076.JPG?raw=1")
fav_donuts_12 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/9o8imtcphenhp5u/Image%20from%20iOS%20%281%29.jpg?raw=1")
fav_donuts_13 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/wcmwskzzq9mkguh/Image%20from%20iOS%20%282%29.jpg?raw=1")
fav_donuts_14 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/wjb56plu0cwdmie/Image%20from%20iOS.jpg?raw=1")
fav_donuts_15 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/vwmmp7r1j12w45w/Image%20from%20iOS%20%284%29.jpg?raw=1")
fav_donuts_16 = Photo.create!(dropbox_link: "https://www.dropbox.com/s/7tj13ln4eunpat2/Image%20from%20iOS%20%283%29.jpg?raw=1")
